apps/Viajes_Management/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import *


urlpatterns = [
    url(r'^viaje$', ViajeList.as_view(), name='Viaje_List'),
    url(r'^viaje/(?P<pk>\d+)/$', ViajeDetail, name='Viaje_Detail'),
    url(r'^viaje/(?P<viaje_id>\d+)/(?P<reserva_id>\d+)/$', AceptarPlaza, name='Aceptar'),
    url(r'^viaje/rechazar/(?P<viaje_id>\d+)/(?P<reserva_id>\d+)/$', RechazarPlaza, name='Rechazar'),
    url(r'^viajeCreate$', ViajeCreate, name='Viaje_Create'),
    url(r'^viajeCreate/agregar$',AgregarParadas, name='Agregar_Paradas'),
    url(r'^viaje/delete/(?P<viaje_id>\d+)/$', ViajeDelete, name='Viaje_Delete'),
    url(r'^viaje/opciones$', Viaje2, name='Viaje2'),
    url(r'^VerPerfil/(?P<pk>\d+)$', VerPerfil1, name='Ver_Perfil1')

]

minerva/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.Core.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
	clients = models.ManyToManyField("Client")
	activeClient = models.ForeignKey("Client",related_name="UsersViewing", null=True, blank=True)
	datos_conductor = models.ForeignKey("Conductor",related_name="DatosConductor", null=True, blank=True)
	correo = models.CharField(max_length=30,null=False, default=" ")
	profesion = models.CharField(max_length=30,null=False, default=" ")
	interes = models.CharField(max_length=30,null=False, default=" ")
	fumador = models.CharField(max_length=30,null=False, default=" ")	
	celular = models.IntegerField(default=123456789)

	foto = models.ImageField(upload_to='user', default="default.png")

	viajes = models.ManyToManyField("Viaje", related_name="user")
	reservas = models.ManyToManyField("Reserva", related_name="user")
	valoraciones = models.ManyToManyField("Valoracion", related_name="user")

	promedioVal = models.FloatField(null=True,blank=True)

	class Meta:
		verbose_name = "User"
		verbose_name_plural = "Users"

	def __unicode__(self):
		return self.username

	

class Client(models.Model):
	name = models.CharField(max_length=15,null=False)
	description = models.TextField(max_length=200,null=False)
	modules = models.ManyToManyField("Module")

	class Meta:
		verbose_name = "Client"
		verbose_name_plural = "Clients"

	def __unicode__(self):
		return self.name	

	
class Module(models.Model):
	name = models.CharField(max_length=30,null=False)
	pathToTemplate = models.CharField(max_length=50,null=False)
	description = models.TextField(max_length=200,null=False)
	
	class Meta:
		verbose_name = "Module"
		verbose_name_plural = "Modules"

	def __unicode__(self):
		return self.name

SCAN_STATUS_CHOICES = (
	("WT", 'En espera'),
	("PA", "Pausado"),
	("RU", "Corriendo"),
	("SC", "Terminado"),
	("ER", "Error"),
	)

class Conductor(models.Model):
	licencia = models.CharField(max_length=30,null=False)
	fecha_obtencion = models.CharField(max_length=30,null=False)
	vehiculo = models.ForeignKey("Vehiculo",related_name="Vehiculo", null=False, default=1)

	class Meta:
		verbose_name = "Conductor"
		verbose_name_plural = "Conductores"

	def __unicode__(self):
		return self.fecha_obtencion

# Falta agregarlo al sistema
class Vehiculo(models.Model):
	marca = models.CharField(max_length=30,null=False)
	modelo = models.CharField(max_length=30,null=False)
	foto_vehiculo = models.ImageField(upload_to='autos')
	color = models.CharField(max_length=15,null=False)
	anno = models.IntegerField(null=True, blank=True, default=1800)
	numero_asientos = models.IntegerField(null=True, blank=True, default=4)
	precio_combustible = models.IntegerField(null=True, blank=True, default=30)

	class Meta:
		verbose_name = "Vehiculo"
		verbose_name_plural = "Vehiculos"

	def __unicode__(self):
		return self.marca + " " + self.modelo

class Viaje(models.Model):
	tarifaPreferencias = models.IntegerField(null=False,blank=True, default=100)
	paradas = models.ManyToManyField("Parada")
	origen = models.ForeignKey("Parada",related_name="ParadaOrigen", null=False, default = 1)
	destino = models.ForeignKey("Parada",related_name="ParadaDestino", null=False, default = 1)
	prestacion = models.ForeignKey("Prestacion",related_name="Prestacion", null=False, default = 1)
	estado =  models.IntegerField(default = -1)
	#conductor = models.ForeignKey("User", related_name = "conductor", null = False, default = 1)
	#-1 En espera
	# 0 Realizando viaje
	# 1 Viaje finalizado y valorado
	# 2 Viaje cercano
	# 3 Viaje finalizado y en valoracion


	class Meta:
		verbose_name = "Viaje"
		verbose_name_plural = "Viajes"

	def __unicode__(self):
		try:
			return  self.origen.nombre.replace("á", 'a').replace("é", 'e').replace("í", 'i').replace("ó", 'o').replace("ú", 'u').replace("ñ", 'n') + " " + self.destino.nombre.replace("á", 'a').replace("é", 'e').replace("í", 'i').replace("ó", 'o').replace("ú", 'u').replace("ñ", 'n')
		except:
			return 'error'

	def verificar(self, cordx1, cordy1, cordx2, cordy2, fecha):
		p1 = self.paradas.filter(coordenada_x__gte=cordx1-0.2).filter(coordenada_x__lte=cordx1+0.2).filter(coordenada_y__gte=cordy1-0.2).filter(coordenada_y__lte=cordy1+0.2)
		if p1.exists():
			p2 = self.paradas.filter(coordenada_x__gte=cordx2-0.2).filter(coordenada_x__lte=cordx2+0.2).filter(coordenada_y__gte=cordy2-0.2).filter(coordenada_y__lte=cordy2+0.2)
			if p2.exists():
				return (p1.first(), p2.first())
		return (-1, -1)

class Prestacion(models.Model):
	max_plazas = models.IntegerField(null=False,blank=False, default=4)
	maletero = models.BooleanField(default=True)
	mascota = models.BooleanField(default=True)
	silla_ninnos = models.BooleanField(default=True)

	class Meta:
		verbose_name = "Prestacion"
		verbose_name_plural = "Prestaciones"

	def __unicode__(self):
		return str(self.max_plazas)

class Parada(models.Model):
	nombre = models.CharField(max_length=30,null=False, default = "Concepcion")
	coordenada_x = models.FloatField(null=True,blank=True)
	coordenada_y = models.FloatField(null=True,blank=True)
	hora = models.CharField(max_length=30,null=True, default = "15:00")
	fecha = models.CharField(max_length=30,null=True, default = "2018/11/12")

	class Meta:
		verbose_name = "Parada"
		verbose_name_plural = "Paradas"

	def __unicode__(self):
		return self.nombre

class Tramo(models.Model):
	km = models.IntegerField(null=True,blank=True)
	precio = models.IntegerField(null=True,blank=True)
	origen = models.ForeignKey("Parada",related_name="ParadaOrigenTramo", null=False, blank=True, default=1)
	destino = models.ForeignKey("Parada",related_name="ParadaDestinoTramo", null=False, blank=True, default=1)
	
	viaje = models.ForeignKey("Viaje",related_name="ViajeTramo", null=False, blank=True, default=1)
	
	class Meta:
		verbose_name = "Tramo"
		verbose_name_plural = "Tramos"

	def __unicode__(self):
		return self.origen.nombre.replace("á", 'a').replace("é", 'e').replace("í", 'i').replace("ó", 'o').replace("ú", 'u').replace("ñ", 'n') + " " + self.destino.nombre.replace("á", 'a').replace("é", 'e').replace("í", 'i').replace("ó", 'o').replace("ú", 'u').replace("ñ", 'n')

class Reserva(models.Model):
	posicion = models.IntegerField(null=True,blank=True)
	estado =  models.IntegerField(default = -1)
	#-1 en espera
	# 0 cancelado
	# 1 aceptado / finalizado
	# 2 terminado / en espera de valoracion
	# 3 aceptado sin notificacion 
	# -2 cancelado sin notificacion 
	# -3 en espera sin notificacion 

	tramo = models.ForeignKey("Tramo",related_name="Tramo", null=False, blank=True, default=1)

	# viaje es igual al del tramo. Se realiza para aumentar la velocidad de la query
	viaje = models.ForeignKey("Viaje",related_name="ViajeReserva", null=False, blank=True, default=1)
	
	class Meta:
		verbose_name = "Reserva"
		verbose_name_plural = "Reservas"

	def __unicode__(self):
		return str(self.posicion) + " " + str(self.estado)

class Valoracion(models.Model):
	puntaje = models.IntegerField(null=True,blank=True)
	comentario = models.CharField(max_length=200,null=False)
	usuario = models.ForeignKey("User",related_name="usuario", null=False, blank=True, default=1)

	class Meta:
		verbose_name = "Valoracion"
		verbose_name_plural = "Valoraciones"

	def __unicode__(self):
		return str(self.puntaje)

apps/Viajes_Management/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import redirect

from django.shortcuts import render

from Core.models import *
from form import *

from datetime import datetime
from datetime import timedelta

# Create your views here.
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.views.generic import TemplateView,ListView
from django.views.generic.detail import DetailView
from django.core.urlresolvers import reverse_lazy

from django.shortcuts import get_object_or_404

class ViajeList(ListView):
	model = Viaje
	template_name = "Viajes_Management/viaje_list.html"
	def get_queryset(self):
		print(self.request.user)
		return self.request.user.viajes.all()

def ViajeCreate(request):
	usuario = request.user
	if request.method == "POST":
		return ViajeCreate4(request)

	return render(request, 'Viajes_Management/viaje_create1.html', {} )

def ViajeCreate4(request):
	usuario = request.user
	if request.method == "POST":
		viaje = Viaje()
		viaje.save()
		viaje.estado = -10

		par1 = Parada()
		par1.nombre =  request.POST.get('origen')
		par1.coordenada_x = request.POST.get('lati1')
		par1.coordenada_y = request.POST.get('long1')
		par1.fecha = request.POST.get('fecha_inicio')
		par1.hora =request.POST.get('hora_inicio')

		par2 = Parada()
		par2.nombre = request.POST.get('destino')
		par2.coordenada_x = request.POST.get('lati2')
		par2.coordenada_y = request.POST.get('long2')
		par2.fecha = request.POST.get('fecha_final')
		print(request.POST.get('fecha_final'))
		_fecha1 = datetime.strptime(par1.fecha, '%Y-%m-%d')
		_fecha2 = datetime.strptime(par2.fecha, '%Y-%m-%d')
		print(_fecha1)
		print(_fecha2)
		print(_fecha2 - _fecha1)
		print(_fecha1 - _fecha2)
		if(_fecha2 - _fecha1 > timedelta(days = 1)): #no viajes largos
			return render(request, 'Viajes_Management/viajes_create.html', {'error_flag': 1})
		elif(_fecha2 - _fecha1 < timedelta(days = 0)): #no viajes en el tiempo
			return render(request, 'Viajes_Management/viajes_create.html', {'error_flag': 2})
		print(type(request.POST.get('fecha_final')))
		#print(par2.fecha - par1.fecha)
		par2.hora = request.POST.get('hora_final')
		par2.save()
		par1.save()

		viaje.origen = par1
		viaje.destino = par2

		viaje.paradas.add(par1)
		viaje.paradas.add(par2)
		usuario.viajes.add(viaje)
		#viaje.conductor = usuario
		viaje.save()
		usuario.save()
		return AgregarParadas(request)
	else:
		form = ViajeForm()
		return render(request, 'Viajes_Management/viajes_create.html', {'form': form} )		
'''
class ViajeDetail(DetailView):
	model = Viaje
	template_name = "Viajes_Management/viaje_detail.html"
'''

def getValor(conductor):
	vals = conductor.first().valoraciones.all()
	suma = 0.0
	for val in vals:
		suma += val.puntaje
	if len(vals) == 0:
		return 0
	return "{0:.2f}".format(suma/len(vals))

def ViajeDetail(request, pk):
	viaje = Viaje.objects.get(id=pk)
	reservas = Reserva.objects.filter(viaje=pk).exclude(estado=0)
	for r in reservas:
		r.user.first().promedioVal = getValor(r.user)
		r.user.first().save()
	return render(request, 'Viajes_Management/viaje_detail.html', {'viaje':viaje, 'reservas':reservas})	

def ViajeDelete(request, viaje_id):
	Viaje.objects.filter(id=viaje_id).delete()
	return render(request, 'Viajes_Management/correcto.html')

def AceptarPlaza(request, viaje_id, reserva_id):
	reserva = Reserva.objects.get(id=reserva_id)
	reserva.estado = 3
	reserva.save()
	return ViajeDetail(request, viaje_id)

def RechazarPlaza(request, viaje_id, reserva_id):
	reserva = Reserva.objects.get(id=reserva_id)
	reserva.estado = -2
	reserva.save()
	return ViajeDetail(request, viaje_id)

def AgregarParadas(request):
	usuario = request.user
	viaje = usuario.viajes.last()

	if request.method == "POST" and viaje.estado != -10:
		
		par2 = Parada()
		par2.nombre = request.POST.get('origen')
		par2.coordenada_x = float(request.POST.get('lati1'))
		par2.coordenada_y = float(request.POST.get('long1'))
		#par2.coordenada_x = 200
		#par2.coordenada_y = 200
		par2.fecha = str(request.POST.get('fecha_inicio'))
		par2.hora = str(request.POST.get('hora_inicio'))

		print(request.POST.get('hora_inicio'))
		print("AAAAAAAAAAAAAa")

		par2.save()
		viaje.paradas.add(par2)

		viaje.save()

		return render(request,'Viajes_Management/agregar_parada.html', {})
	else:
		viaje.estado = -9
		viaje.save()
		return render(request, 'Viajes_Management/agregar_parada.html', {} )

def ObtenerPromedio():
	viajes = Viaje.objects.all()
	suma = 0
	for v in viajes: suma += v.tarifaPreferencias
	return suma / len(viajes)

def Viaje2(request):
	usuario = request.user
	viaje = usuario.viajes.last()

	if request.method == "POST" and viaje.estado != -9:
		form = ViajeForm(request.POST)
		if form.is_valid():

			prestacion = Prestacion()
			prestacion.max_plazas = form.cleaned_data['plazas']
			prestacion.maletero = form.cleaned_data['maletero']
			prestacion.mascota = form.cleaned_data['mascota']
			prestacion.silla_ninnos = form.cleaned_data['silla']

			viaje.tarifaPreferencias = form.cleaned_data['tarifa']

			prestacion.save()
			viaje.prestacion = prestacion
			viaje.estado = -1

			viaje.save()
			return render(request, 'Viajes_Management/correcto2.html')
	else:
		form = ViajeForm()
		viaje.estado = -8
		viaje.save()

		tarifa = ObtenerPromedio()

		return render(request, 'Viajes_Management/Viaje2.html', {'form': form, 'tarifa': tarifa} )		

def VerPerfil1(request, pk):
	user = User.objects.get(id = pk)
	num_vals = len(user.valoraciones.all())
	if (num_vals >= 3):
		valoraciones = user.valoraciones.all().order_by('-id')[:3]
	else:
		valoraciones = user.valoraciones.all().order_by('-id')[:num_vals]
	return render(request, "Perfil_Management/perfil_detail22.html", {'usuario': user, 'flag': True, 'valoraciones': valoraciones, 'n': num_vals})

apps/Viajes_Management/templates/Viajes_Management/Viaje2.html
<!DOCTYPE html>
<html>
  <head>
    <title>Create Viaje</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
       #map {
    width: 25%;
    height: 300px;
}
    #map2{
    width: 25%;
    height: 300px;
}
.controls {
    margin-top: 10px;
    border: 1px solid transparent;
    border-radius: 2px 0 0 2px;
    box-sizing: border-box;
    -moz-box-sizing: border-box;
    height: 32px;
    outline: none;
    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
}
    </style>
  </head>
{% extends 'base.html' %}

{% block content %}

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Creación de viaje </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <p class="text-muted font-13 m-b-30">
                    </p>
                     <br>
                   </div>
          <form action="" method="POST">
          {% csrf_token %}

    {{ form.as_p }}

    <h2> Tarifa promedio del sistema: {{tarifa}} </h2>

    <input type="submit" value="Submit" />
</form>
<script>
            
</script>
          </script>

{% endblock %}

{% block scripts %}
    {% load static %}
    <!-- Datatables -->
    <script src="{% static 'js/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
    <script src="{% static 'js/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'js/jszip/dist/jszip.min.js' %}"></script>
    <script src="{% static 'js/pdfmake/build/pdfmake.min.js' %}"></script>
    <script src="{% static 'js/pdfmake/build/vfs_fonts.js' %}"></script>

<script>
$(document).ready(function() {
    $('#datatable-inbox').DataTable( {
      "searching": false,
      "paging": false,
      "info": false
    } );
} );
</script>

{% endblock %}

apps/Viajes_Management/templates/Viajes_Management/agregar_parada.html
<!DOCTYPE html>
<html>
  <head>
    <title>Create Viaje</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
       #map {
    width: 25%;
    height: 300px;
}
    #map2{
    width: 25%;
    height: 300px;
}
.controls {
    margin-top: 10px;
    border: 1px solid transparent;
    border-radius: 2px 0 0 2px;
    box-sizing: border-box;
    -moz-box-sizing: border-box;
    height: 32px;
    outline: none;
    box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
}
.button {
    color: green;
}
    </style>
  </head>
{% extends 'base.html' %}

{% block content %}

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Creación de viaje </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <p class="text-muted font-13 m-b-30">
                    </p>
                     <br>
                   </div>

                   <h3> Agregar parada </h3>
          <form action="{% url "Agregar_Paradas" %}" method="POST">
          {% csrf_token %}
               <div style="font-weight:bold">
                  Origen: <input type="text" input id="searchInput"  name = "origen" required class="vTextField" maxlength="30" />
              </div>
              <br>
            <div id="map"></div>
            <br>
            <ul id="geoData">
                <li>Full Address: <span id="location"></span></li>
                <li>Country: <span id="country"></span></li>
                <li>Latitude: <span id="lat"></span></li>
                <li>Longitude: <span id="long"></span></li>
                <br>
                <input type="hidden" id = "lati1" name="lati1" value="" />
                <input type="hidden" id = "long1" name="long1" value="" />
            </ul>
            <div class="form-row field-fecha">
                <div>
                  <label class="required" for="fecha_inicio">Fecha de inicio:</label>
                    <input type="date" name="fecha_inicio" value = "MM/DD/YY" id="id_fecha"/>
                </div>
              </div>
              <br>
           <div class="form-row field-hora">
            <div>
              <label class="required" for="hora_inicio">Hora de inicio:</label>
              <input type="time" name="hora_inicio" value = "HH:MM" id="id_hora"/>
            </div>
          </div>
                <br>
                  <div>
                  <h3> ¿Quiere ingresar la parada al nuevo viaje? </h3>
                     <input type="submit" value="Agregar Parada" style="background-color: #00cc7a; /* Green */border: none;color: white;padding: 11px;text-align: center;text-decoration: none;display: inline-block;font-size: 12px;margin: 4px 2px;border-radius: 21px;">
                     <br> <br>

                     <h3> ¿No quiere agregar más paradas? </h3>
                     <td><a href="{% url "Viaje2" %}" type="button" class="btn btn-round btn-info btn-sm">Continuar</a></td>
                  </div>
                </form>
                  <br>
             <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAD6Q31QwQK0pv7twtzD32efp6hLa0uFEs&libraries=places&callback=initMap" async defer></script>
<script>
          function initMap() {
              var map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: -33.8688, lng: 151.2195},
                zoom: 13
              });

              var input = document.getElementById('searchInput');

              var autocomplete = new google.maps.places.Autocomplete(input);
              autocomplete.bindTo('bounds', map);

              var infowindow = new google.maps.InfoWindow();
              var marker = new google.maps.Marker({
                  map: map,
                  anchorPoint: new google.maps.Point(0, -29)
              });

              autocomplete.addListener('place_changed', function() {
                  infowindow.close();
                  marker.setVisible(false);
                  var place = autocomplete.getPlace();
                  if (!place.geometry) {
                      window.alert("Autocomplete's returned place contains no geometry");
                      return;
                  }
            
                  // If the place has a geometry, then present it on a map.
                  if (place.geometry.viewport) {
                      map.fitBounds(place.geometry.viewport);
                  } else {
                      map.setCenter(place.geometry.location);
                      map.setZoom(17);
                  }
                  marker.setIcon(({
                      url: place.icon,
                      size: new google.maps.Size(71, 71),
                      origin: new google.maps.Point(0, 0),
                      anchor: new google.maps.Point(17, 34),
                      scaledSize: new google.maps.Size(35, 35)
                  }));
                  marker.setPosition(place.geometry.location);
                  marker.setVisible(true);
              
                  var address = '';
                  if (place.address_components) {
                      address = [
                        (place.address_components[0] && place.address_components[0].short_name || ''),
                        (place.address_components[1] && place.address_components[1].short_name || ''),
                        (place.address_components[2] && place.address_components[2].short_name || '')
                      ].join(' ');
                  }
              
                  infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
                  infowindow.open(map, marker);
                
                  //Location details
                  for (var i = 0; i < place.address_components.length; i++) {
                      if(place.address_components[i].types[0] == 'postal_code'){
                          document.getElementById('postal_code').innerHTML = place.address_components[i].long_name;
                      }
                      if(place.address_components[i].types[0] == 'country'){
                          document.getElementById('country').innerHTML = place.address_components[i].long_name;
                      }
                  }
                  document.getElementById('location').innerHTML = place.formatted_address;
                  document.getElementById('lat').innerHTML = place.geometry.location.lat();
                  document.getElementById('long').innerHTML = place.geometry.location.lng();
                  document.getElementById('lati1').value = place.geometry.location.lat();
                  document.getElementById('long1').value = place.geometry.location.lng();
              });
             } 
            
</script>
          </script>

{% endblock %}

{% block scripts %}
    {% load static %}
    <!-- Datatables -->
    <script src="{% static 'js/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
    <script src="{% static 'js/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'js/jszip/dist/jszip.min.js' %}"></script>
    <script src="{% static 'js/pdfmake/build/pdfmake.min.js' %}"></script>
    <script src="{% static 'js/pdfmake/build/vfs_fonts.js' %}"></script>

<script>
$(document).ready(function() {
    $('#datatable-inbox').DataTable( {
      "searching": false,
      "paging": false,
      "info": false
    } );
} );
</script>

{% endblock %}

apps/Viajes_Management/templates/Viajes_Management/menu.html
<li><a><i class="fa fa-taxi"></i> Viajes <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url "Viaje_Create" %}">Crear Viajes</a></li>
                      <li><a href="{% url "Viaje_List" %}">Ver Viajes</a></li>
                    </ul>
                  </li>