apps/Perfil_Management/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import *


urlpatterns = [

    url(r'^perfil/(?P<pk>\d+)$', PerfilDetail, name='Perfil_Detail'),
    url(r'^inicio/$', inicio, name='inicio'),
    url(r'^MasValoraciones/(?P<pk>\d+)$', MasValoraciones, name='MasValoraciones'),
    url(r'^change_password/$', change_password, name='change_password'),
    url(r'^perfil/edit/(?P<pk>\d+)$', PerfilEdit.as_view(), name='Perfil_Edit'),
    url(r'^EditarPerfil/$', EditarPerfil, name='EditarPerfil'),
    url(r'^EditarFoto/$', EditarFoto, name='EditarFoto'),
    url(r'^EditarVehiculo/$', EditarVehiculo, name='EditarVehiculo'),
    url(r'^EditarFotoVehiculo/$', EditarFotoVehiculo, name='EditarFotoVehiculo'),
    url(r'^VerPerfil/(?P<pk>\d+)$', VerPerfil, name='VerPerfil'),
    url(r'^DetalleVehiculo/(?P<pk>\d+)$', DetalleVehiculo, name='DetalleVehiculo'),
    url(r'^Valorar/(?P<pk>\d+)/(?P<tipo>\w+)/(?P<reserva_id>\d+)/(?P<usuario_id>\d+)/$', Valorar, name='Valorar'),
    url(r'^Administrar/Pasa/(?P<viaje_id>\d+)/(?P<reserva_id>\d+)/$', ValorarPasajero, name='Valorar_Pasajero'),
    url(r'^Administrar/Pasa2/(?P<viaje_id>\d+)/(?P<reserva_id>\d+)/$', ValorarConductor, name='Valorar_Conductor'),
#    url(r'^buscar_error$', Buscar, name='Buscar_Create'),
#    url(r'^show/$', BuscarList.as_view() , name='show')

]

minerva/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.Core.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
	clients = models.ManyToManyField("Client")
	activeClient = models.ForeignKey("Client",related_name="UsersViewing", null=True, blank=True)
	datos_conductor = models.ForeignKey("Conductor",related_name="DatosConductor", null=True, blank=True)
	correo = models.CharField(max_length=30,null=False, default=" ")
	profesion = models.CharField(max_length=30,null=False, default=" ")
	interes = models.CharField(max_length=30,null=False, default=" ")
	fumador = models.CharField(max_length=30,null=False, default=" ")	
	celular = models.IntegerField(default=123456789)

	foto = models.ImageField(upload_to='user', default="default.png")

	viajes = models.ManyToManyField("Viaje", related_name="user")
	reservas = models.ManyToManyField("Reserva", related_name="user")
	valoraciones = models.ManyToManyField("Valoracion", related_name="user")

	promedioVal = models.FloatField(null=True,blank=True)

	class Meta:
		verbose_name = "User"
		verbose_name_plural = "Users"

	def __unicode__(self):
		return self.username

	

class Client(models.Model):
	name = models.CharField(max_length=15,null=False)
	description = models.TextField(max_length=200,null=False)
	modules = models.ManyToManyField("Module")

	class Meta:
		verbose_name = "Client"
		verbose_name_plural = "Clients"

	def __unicode__(self):
		return self.name	

	
class Module(models.Model):
	name = models.CharField(max_length=30,null=False)
	pathToTemplate = models.CharField(max_length=50,null=False)
	description = models.TextField(max_length=200,null=False)
	
	class Meta:
		verbose_name = "Module"
		verbose_name_plural = "Modules"

	def __unicode__(self):
		return self.name

SCAN_STATUS_CHOICES = (
	("WT", 'En espera'),
	("PA", "Pausado"),
	("RU", "Corriendo"),
	("SC", "Terminado"),
	("ER", "Error"),
	)

class Conductor(models.Model):
	licencia = models.CharField(max_length=30,null=False)
	fecha_obtencion = models.CharField(max_length=30,null=False)
	vehiculo = models.ForeignKey("Vehiculo",related_name="Vehiculo", null=False, default=1)

	class Meta:
		verbose_name = "Conductor"
		verbose_name_plural = "Conductores"

	def __unicode__(self):
		return self.fecha_obtencion

# Falta agregarlo al sistema
class Vehiculo(models.Model):
	marca = models.CharField(max_length=30,null=False)
	modelo = models.CharField(max_length=30,null=False)
	foto_vehiculo = models.ImageField(upload_to='autos')
	color = models.CharField(max_length=15,null=False)
	anno = models.IntegerField(null=True, blank=True, default=1800)
	numero_asientos = models.IntegerField(null=True, blank=True, default=4)
	precio_combustible = models.IntegerField(null=True, blank=True, default=30)

	class Meta:
		verbose_name = "Vehiculo"
		verbose_name_plural = "Vehiculos"

	def __unicode__(self):
		return self.marca + " " + self.modelo

class Viaje(models.Model):
	tarifaPreferencias = models.IntegerField(null=False,blank=True, default=100)
	paradas = models.ManyToManyField("Parada")
	origen = models.ForeignKey("Parada",related_name="ParadaOrigen", null=False, default = 1)
	destino = models.ForeignKey("Parada",related_name="ParadaDestino", null=False, default = 1)
	prestacion = models.ForeignKey("Prestacion",related_name="Prestacion", null=False, default = 1)
	estado =  models.IntegerField(default = -1)
	#conductor = models.ForeignKey("User", related_name = "conductor", null = False, default = 1)
	#-1 En espera
	# 0 Realizando viaje
	# 1 Viaje finalizado y valorado
	# 2 Viaje cercano
	# 3 Viaje finalizado y en valoracion


	class Meta:
		verbose_name = "Viaje"
		verbose_name_plural = "Viajes"

	def __unicode__(self):
		try:
			return  self.origen.nombre.replace("á", 'a').replace("é", 'e').replace("í", 'i').replace("ó", 'o').replace("ú", 'u').replace("ñ", 'n') + " " + self.destino.nombre.replace("á", 'a').replace("é", 'e').replace("í", 'i').replace("ó", 'o').replace("ú", 'u').replace("ñ", 'n')
		except:
			return 'error'

	def verificar(self, cordx1, cordy1, cordx2, cordy2, fecha):
		p1 = self.paradas.filter(coordenada_x__gte=cordx1-0.2).filter(coordenada_x__lte=cordx1+0.2).filter(coordenada_y__gte=cordy1-0.2).filter(coordenada_y__lte=cordy1+0.2)
		if p1.exists():
			p2 = self.paradas.filter(coordenada_x__gte=cordx2-0.2).filter(coordenada_x__lte=cordx2+0.2).filter(coordenada_y__gte=cordy2-0.2).filter(coordenada_y__lte=cordy2+0.2)
			if p2.exists():
				return (p1.first(), p2.first())
		return (-1, -1)

class Prestacion(models.Model):
	max_plazas = models.IntegerField(null=False,blank=False, default=4)
	maletero = models.BooleanField(default=True)
	mascota = models.BooleanField(default=True)
	silla_ninnos = models.BooleanField(default=True)

	class Meta:
		verbose_name = "Prestacion"
		verbose_name_plural = "Prestaciones"

	def __unicode__(self):
		return str(self.max_plazas)

class Parada(models.Model):
	nombre = models.CharField(max_length=30,null=False, default = "Concepcion")
	coordenada_x = models.FloatField(null=True,blank=True)
	coordenada_y = models.FloatField(null=True,blank=True)
	hora = models.CharField(max_length=30,null=True, default = "15:00")
	fecha = models.CharField(max_length=30,null=True, default = "2018/11/12")

	class Meta:
		verbose_name = "Parada"
		verbose_name_plural = "Paradas"

	def __unicode__(self):
		return self.nombre

class Tramo(models.Model):
	km = models.IntegerField(null=True,blank=True)
	precio = models.IntegerField(null=True,blank=True)
	origen = models.ForeignKey("Parada",related_name="ParadaOrigenTramo", null=False, blank=True, default=1)
	destino = models.ForeignKey("Parada",related_name="ParadaDestinoTramo", null=False, blank=True, default=1)
	
	viaje = models.ForeignKey("Viaje",related_name="ViajeTramo", null=False, blank=True, default=1)
	
	class Meta:
		verbose_name = "Tramo"
		verbose_name_plural = "Tramos"

	def __unicode__(self):
		return self.origen.nombre.replace("á", 'a').replace("é", 'e').replace("í", 'i').replace("ó", 'o').replace("ú", 'u').replace("ñ", 'n') + " " + self.destino.nombre.replace("á", 'a').replace("é", 'e').replace("í", 'i').replace("ó", 'o').replace("ú", 'u').replace("ñ", 'n')

class Reserva(models.Model):
	posicion = models.IntegerField(null=True,blank=True)
	estado =  models.IntegerField(default = -1)
	#-1 en espera
	# 0 cancelado
	# 1 aceptado / finalizado
	# 2 terminado / en espera de valoracion
	# 3 aceptado sin notificacion 
	# -2 cancelado sin notificacion 
	# -3 en espera sin notificacion 

	tramo = models.ForeignKey("Tramo",related_name="Tramo", null=False, blank=True, default=1)

	# viaje es igual al del tramo. Se realiza para aumentar la velocidad de la query
	viaje = models.ForeignKey("Viaje",related_name="ViajeReserva", null=False, blank=True, default=1)
	
	class Meta:
		verbose_name = "Reserva"
		verbose_name_plural = "Reservas"

	def __unicode__(self):
		return str(self.posicion) + " " + str(self.estado)

class Valoracion(models.Model):
	puntaje = models.IntegerField(null=True,blank=True)
	comentario = models.CharField(max_length=200,null=False)
	usuario = models.ForeignKey("User",related_name="usuario", null=False, blank=True, default=1)

	class Meta:
		verbose_name = "Valoracion"
		verbose_name_plural = "Valoraciones"

	def __unicode__(self):
		return str(self.puntaje)

apps/Perfil_Management/forms.py
from django import forms
from django.forms import widgets
from models import *
from Core.models import *


class PerfilEditForm(forms.ModelForm):
    fumador = forms.TypedChoiceField(
                   coerce=lambda x: x == 'True',
                   choices=((False, 'False'), (True, 'True')),
                   widget=forms.RadioSelect, 
                   initial = False)
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'profesion', 'interes', 'fumador', 'celular')

class UploadImageForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('foto',)

class UploadCarImageForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = ('foto_vehiculo',)

class VehiculoEditForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = ('marca', 'modelo', 'color', 'anno', 'numero_asientos', 'precio_combustible')

apps/Perfil_Management/templates/Perfil_Management/menu.html
<li><a><i class="fa fa-user"></i> Perfil <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url "VerPerfil" user.id %}">Ver Perfil</a></li>
                    <li><a href="{% url "EditarPerfil"%}">Editar Perfil</a></li>
                    <li><a href="{% url "EditarFoto"%}">Editar Foto de Perfil</a></li>
                    <li><a href="{% url "change_password"%}">Cambiar Contraseña</a></li>
                    {% if user.activeClient.name == "Conductor" %}
                    <li><a href="{% url "EditarVehiculo"%}">Editar Info. Vehiculo</a></li>
                    <li><a href="{% url "EditarFotoVehiculo"%}">Editar Foto del Vehiculo</a></li>
                    {% endif %}
                  </li>
                  </ul>
                  </li>

apps/Perfil_Management/templates/Perfil_Management/perfil_detail3.html
{% extends 'base.html' %}
{% block content %}

             <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <br>
                    <h2>Usuario: {{user.first_name}} {{user.last_name}}</h2> 
                    
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <p class="text-muted font-13 m-b-30"></p>
                    <h1>{{errores.as_data}}</h1>
                  <!--<div class="form-row field-foto">
                    <div>
                      <label class="required" for="id_foto">Foto:</label>
                      <p class="file-upload">Currently: <a href= {{user.foto}} >default.png</a><br>Change:
                      <input type="file" name="foto" id="id_foto" /></p>
                    </div>
                  </div>
                  <div class="submit-row">
                    <input type="submit" value="Save" class="default" name="_save" />
                  </div> -->
              </div>
              </div>



{% endblock %}

{% block scripts %}
    {% load static %}
    <!-- Datatables -->
    <script src="{% static 'js/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
    <script src="{% static 'js/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'js/jszip/dist/jszip.min.js' %}"></script>
    <script src="{% static 'js/pdfmake/build/pdfmake.min.js' %}"></script>
    <script src="{% static 'js/pdfmake/build/vfs_fonts.js' %}"></script>


{% endblock %}

apps/Perfil_Management/templates/Perfil_Management/perfil_edit.html
{% extends 'base.html' %}
{% block content %}

             <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <br>
                    <h2>Usuario: {{user.first_name}} {{user.last_name}}</h2> 
                    
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <p class="text-muted font-13 m-b-30"></p>
                  <div class="form-row field-correo">
                    <div>
                        <label class="required" for="id_correo">Correo:</label>
                        <input type="text" name="correo" value = {{user.correo}} id="id_correo" required class="vTextField" maxlength="30" />
                    </div>
                  </div>
                  <br>
                  <div class="form-row field-profesion">
                    <div>
                      <label class="required" for="id_profesion">Profesion:</label>
                      <input type="text" name="profesion" value = {{user.profesion}} id="id_profesion" required class="vTextField" maxlength="30" />
                    </div>
                  </div>
                  <br>
                  <div class="form-row field-interes">
                    <div>
                      <label class="required" for="id_interes">Interes:</label>
                      <input type="text" name="interes" value = {{user.interes}} id="id_interes" required class="vTextField" maxlength="30" />
                    </div>
                  </div>
                  <br>
                  <div class="form-row field-fumador">
                    <div>
                      <label class="required" for="id_fumador">Fumador:</label>
                      <input type="text" name="fumador" value = {{user.fumador}} id="id_fumador" required class="vTextField" maxlength="30" />    
                    </div>
                  </div>
                  <br>
                  <div class="form-row field-celular">
                    <div>
                      <label class="required" for="id_celular">Celular:</label>
                      <input type="text" name="celular" value = {{user.celular}} id="id_celular" required class="vTextField" maxlength="30" />    
                    </div>
                  </div>
                  <br>
                  <div class="form-row field-foto">
                    <div>
                      <label class="required" for="id_foto">Foto:</label>
                      <p class="file-upload">Currently: <a href= {{user.foto}} >default.png</a><br>Change:
                      <input type="file" name="foto" id="id_foto" /></p>
                    </div>
                  </div>
                  <div class="submit-row">
                    <input type="submit" value="Save" class="default" name="_save" />
                  </div>
              </div>
              </div>



{% endblock %}

{% block scripts %}
    {% load static %}
    <!-- Datatables -->
    <script src="{% static 'js/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
    <script src="{% static 'js/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'js/jszip/dist/jszip.min.js' %}"></script>
    <script src="{% static 'js/pdfmake/build/pdfmake.min.js' %}"></script>
    <script src="{% static 'js/pdfmake/build/vfs_fonts.js' %}"></script>


{% endblock %}

apps/Perfil_Management/templates/Perfil_Management/perfil_edit2.html
{% extends 'base.html' %}
{% block content %}
<style>
  /* Create two equal columns that floats next to each other */
.column {
  float: left;
  width: 30%;
  padding: 10px;
  height: 500px; /* Should be removed. Only for demonstration */
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>
             <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <br>
                    <h2>Usuario: {{user.first_name}} {{user.last_name}}</h2> 
                    
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <p class="text-muted font-13 m-b-30"></p>
                    <font color="red"><h4>**Todos los campos son obligatorios**</h4></font>
                    <div class = "column">
                      <form method = "POST" class="post-form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <h4>Nombre</h4>
                        {{form.first_name}}
                        <h4>Apellido</h4>
                        {{form.last_name}}
                        <h4>Correo electrónico</h4>
                        {{form.email}}
                        <h4>Profesión</h4>
                        {{form.profesion}}
                        <h4>Intereses</h4>
                        {{form.interes}}
                        <h4>Fumador</h4>
                        {{form.fumador}}
                        <h4>Celular</h4>
                        {{form.celular}}
                        <button type="submit" class="save btn btn-default">Guardar</button>
                      </form>
                    </div>
                  <!--<div class="form-row field-foto">
                    <div>
                      <label class="required" for="id_foto">Foto:</label>
                      <p class="file-upload">Currently: <a href= {{user.foto}} >default.png</a><br>Change:
                      <input type="file" name="foto" id="id_foto" /></p>
                    </div>
                  </div>
                  <div class="submit-row">
                    <input type="submit" value="Save" class="default" name="_save" />
                  </div> -->
              </div>
              </div>



{% endblock %}

{% block scripts %}
    {% load static %}
    <!-- Datatables -->
    <script src="{% static 'js/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
    <script src="{% static 'js/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'js/jszip/dist/jszip.min.js' %}"></script>
    <script src="{% static 'js/pdfmake/build/pdfmake.min.js' %}"></script>
    <script src="{% static 'js/pdfmake/build/vfs_fonts.js' %}"></script>


{% endblock %}

apps/Perfil_Management/templates/Perfil_Management/perfil_image_edit.html
{% extends 'base.html' %}
{% block content %}
<style>
  /* Create two equal columns that floats next to each other */
.column {
  float: left;
  width: 30%;
  padding: 10px;
  height: 500px; /* Should be removed. Only for demonstration */
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>
             <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <br>
                    <h2>Usuario: {{user.first_name}} {{user.last_name}}</h2> 
                    
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <p class="text-muted font-13 m-b-30"></p>
                    <div class = "column" align = "center">
                      <p class="text-muted font-13 m-b-30"></p>
                      <a> <img src="/media/{{user.foto}}" width="120px"> </a>
                    </div>
                    <div class = "column">
                      <form method="POST" class = "post-form" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="save btn btn-default">Guardar</button>
                      </form>
                    </div>
                  <!--<div class="form-row field-foto">
                    <div>
                      <label class="required" for="id_foto">Foto:</label>
                      <p class="file-upload">Currently: <a href= {{user.foto}} >default.png</a><br>Change:
                      <input type="file" name="foto" id="id_foto" /></p>
                    </div>
                  </div>
                  <div class="submit-row">
                    <input type="submit" value="Save" class="default" name="_save" />
                  </div> -->
              </div>
              </div>



{% endblock %}

{% block scripts %}
    {% load static %}
    <!-- Datatables -->
    <script src="{% static 'js/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'js/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
    <script src="{% static 'js/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'js/jszip/dist/jszip.min.js' %}"></script>
    <script src="{% static 'js/pdfmake/build/pdfmake.min.js' %}"></script>
    <script src="{% static 'js/pdfmake/build/vfs_fonts.js' %}"></script>


{% endblock %}